#override defaults for dev
version: "3.7"

services:
  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - 80:80
      - 3306:3306
      - 22:22
      - 8888:8888
      - 9999:9999
    volumes:
        - "db_volume:/var/lib/mysql"
        - /Users/Sebastian.Kirejewski/projekte/sw6prod:/var/www/html:rw
    networks:
        - web
    environment:
        - XDEBUG_ENABLED=1

volumes:
    db_volume:
        driver: local

networks:
    web:
        external: false
